export const datas = [
	{
		final_price: 79000,
		image: "https://canifa.com/img/500/750/resize/8/u/8us22a008-sa705-xl-1.jpg",
		meta_title: "Combo 2 quần sịp đùi nam dáng ôm 8US22A008",
		meta_description: "Đồ lót. Pack 2 quần sịp đùi nam",
		name: "Combo 2 quần sịp đùi nam dáng ôm",
		short_description: "Quần sịp đùi chất liệu cotton spandex.\nPhom ôm sát.",
		status: 1,
		url_path: "quan-sip-nam-8us22a008",
		sku: "8US22A008",
		slug: "quan-sip-nam-8us22a008",
		stock: 243665,
		materials: "95% cotton 5% spandex",
		main_category: "Sale corner",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy khô ở nhiệt độ thấp.\nKhông được là.\nGiặt với sản phẩm cùng màu.",
	},
	{
		final_price: 99000,
		image: "https://canifa.com/img/500/750/resize/8/u/8us22a009-sk238-xl-1.jpg",
		meta_title: "Combo 2 quần sịp tam giác nam dáng ôm sát 8US22A009",
		meta_description: "Đồ lót. Pack 2 quần sịp tam giác nam",
		name: "Combo 2 quần sịp tam giác nam dáng ôm sát",
		short_description: "Quần sịp tam giác chất liệu cotton spandex.\nPhom ôm sát.",
		status: 1,
		url_path: "quan-sip-nam-8us22a009",
		sku: "8US22A009",
		slug: "quan-sip-nam-8us22a009",
		stock: 243674,
		materials: "95% cotton 5% spandex",
		main_category: "Sale corner",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy khô ở nhiệt độ thấp.\nKhông được là.\nGiặt với sản phẩm cùng màu.",
	},
	{
		final_price: 479200,
		image: "https://canifa.com/img/500/750/resize/6/b/6bp24w009-sn027-l-1-u.jpg",
		meta_title: "Quần nỉ nữ 6BP24W009",
		meta_description: "Quần nỉ nữ. Quần jogger nữ. Quần jogger.",
		name: "Quần nỉ nữ",
		short_description:
			"Quần nỉ nữ dáng jogger, chất liệu dệt siêu mịn và mướt, các chi tiết phối lé điểm nhấn, tạo nên một sản phẩm tinh tế và đắt giá.",
		status: 1,
		sku: "6BP24W009",
		slug: "quan-jogger-nu-6bp24w009",
		stock: 278617,
		materials: "50% polyester 45% rayon 5% spandex.",
		main_category: "Quần nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy khô ở nhiệt độ thấp.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 244300,
		image: "https://canifa.com/img/500/750/resize/1/t/1te23w005-fb488-1-thumbjpg.jpg",
		meta_title: "Áo gilet len bé gái cổ tim 1TE23W005",
		meta_description: "Áo len gilet bé gái",
		name: "Áo gilet len bé gái cổ tim",
		short_description:
			"Áo gilet len cổ tim, chất liệu len dày dặn và mềm mại giúp bé có cảm giác dễ chịu và ấm áp, kiểu dáng lửng có thể phối hợp linh hoạt các kiểu trang phục khác nhau.\r\nChất liệu kết hợp giữa sợi len nhân tạo acrylic và polyester giúp sản phẩm mềm mại. Màu sắc rất đa dạng, bắt mắt.",
		status: 1,
		url_path: "ao-len-gilet-be-trai-1te23w005",
		sku: "1TE23W005",
		slug: "ao-len-gilet-be-trai-1te23w005",
		stock: 263071,
		materials: "60% nylon 20% acrylic 20% polyester",
		main_category: "Áo trẻ em",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường. Không sử dụng hóa chất tẩy. Phơi vắt ngang, trong bóng mát. Không sử dụng máy sấy. Là ở nhiệt độ thấp 110 độ c. Có thể giặt khô. Sử dụng túi lưới để giặt.",
		is_pre_order: false,
	},
	{
		final_price: 399200,
		image: "https://canifa.com/img/500/750/resize/1/d/1ds24c015-sr002-134-1-u.jpg",
		meta_title: "Váy liền bé gái 1DS24C015",
		meta_description: "Váy liền bé gái. Váy bé gái. Đầm liền bé gái. Đầm bé gái. Đầm trẻ em. Váy trẻ em.",
		name: "Váy liền bé gái",
		short_description:
			"Váy liền bé gái, các chi tiết rúm bèo, tay bồng mang lại sự nữ tính cho bé gái. Chất liệu nhung rất mềm mại phù hợp mặc trong các dịp lễ tết",
		status: 1,
		sku: "1DS24C015",
		slug: "vay-lien-be-gai-1ds24c015",
		stock: 277656,
		materials: "93% polyester 7% spandex.",
		main_category: "Váy liền thân",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nKhông được là.\nGiặt với sản phẩm cùng màu.",
		is_pre_order: false,
	},
	{
		final_price: 519200,
		image: "https://canifa.com/img/500/750/resize/5/t/5tw24w001-sg646-m-1-u.jpg",
		meta_title: "Áo hoodie unisex người lớn 5TW24W001-SG646",
		meta_description: "Áo nỉ có mũ unisex người lớn. Áo hoodie. Áo hoodie nam. Áo hoodie nữ.",
		name: "Áo nỉ có mũ unisex người lớn",
		short_description: "Áo nỉ có mũ unisex người lớn",
		status: 1,
		sku: "5TW24W001-SG646",
		slug: "ao-hoodie-unisex-nguoi-lon-5tw24w001-sg646",
		stock: 278893,
		materials: "60% cotton 40% polyester.",
		main_category: "Hàng mới",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy thùng, chế độ nhẹ nhàng.\nLà ở nhiệt độ trung bình 150 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 209300,
		image: "https://canifa.com/img/500/750/resize/2/t/2tw23w014-sb227-thumb.jpg",
		meta_title: "Áo nỉ bé trai cotton USA có hình in 2TW23W014",
		meta_description: "Áo nỉ bé trai",
		name: "Áo nỉ bé trai cotton USA có hình in",
		short_description:
			"Áo nỉ bé trai phong cách sport. Mix màu tay áo, chất liệu nỉ dày dặn ấm áp cho mùa đông, phom dáng regular thoải mái. Hình in chữ khỏe khoắn năng động phù hợp cho bé trong nhiều hoàn cảnh sử dụng.\r\nChất liệu cotton USA.",
		status: 1,
		url_path: "ao-ni-be-trai-2tw23w014",
		sku: "2TW23W014",
		slug: "ao-ni-be-trai-2tw23w014",
		stock: 262708,
		materials: "Vải chính: 60% cotton 40% polyester.\r\nVải phối: 60% cotton 40% polyester.",
		main_category: "Sale corner",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.\r\nKhông được ngâm.",
		is_pre_order: false,
	},
	{
		final_price: 479200,
		image: "https://canifa.com/img/500/750/resize/6/b/6bp24w003-se178-m-1-u.jpg",
		meta_title: "Quần dài nữ 6BP24W003",
		meta_description: "Quần dài nữ",
		name: "Quần dài nữ dáng suông, gấu lơ vê",
		short_description:
			"Quần dài nữ dáng suông rộng vừa, gấu lơ vê. Chất liệu mềm mại, đứng dáng. Thiết kế với độ rộng vừa phải, phù hợp môi trường lịch sự, văn phòng, công sở.",
		status: 1,
		sku: "6BP24W003",
		slug: "quan-dai-nu-6bp24w003",
		stock: 277421,
		materials: "100% polyester.",
		main_category: "Quần vải",
		instruction:
			"Giặt tay ở nhiệt độ thường,không ngâm.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 799200,
		image: "https://canifa.com/img/500/750/resize/6/o/6ot24w025-sn326-l-1-u.jpg",
		meta_title: "Áo khoác gilet chần bông nữ 6OT24W025",
		meta_description: "Áo khoác gilet chần bông nữ. Áo gilet chần bông. Áo chần bông gilet.",
		name: "Áo khoác gilet chần bông nữ",
		short_description:
			"Áo khoác ghi lê bông thổi kéo khóa của nữ, chi tiết rút eo, có thể thay đổi kiểu mặc cho người sử dụng. Phù hợp với thời tiết lạnh sâu và có khả năng chống thấm nhẹ.",
		status: 1,
		sku: "6OT24W025",
		slug: "ao-khoac-chan-bong-gilet-nu-6ot24w025",
		stock: 278950,
		main_category: "Áo khoác chần bông",
		is_pre_order: false,
	},
	{
		final_price: 519200,
		image: "https://canifa.com/img/500/750/resize/5/t/5tw24w001-sm176-m-1-u.jpg",
		meta_title: "Áo nỉ có mũ unisex người lớn 5TW24W001-SM176",
		meta_description: "Áo nỉ có mũ unisex người lớn. Áo hoodie. Áo hoodie nam. Áo hoodie nữ.",
		name: "Áo nỉ có mũ unisex người lớn",
		short_description: "Áo nỉ có mũ unisex người lớn",
		status: 1,
		sku: "5TW24W001-SM176",
		slug: "ao-hoodie-unisex-nguoi-lon-5tw24w001-sm176",
		stock: 278891,
		materials: "60% cotton 40% polyester.",
		main_category: "Hàng mới",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy thùng, chế độ nhẹ nhàng.\nLà ở nhiệt độ trung bình 150 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 519200,
		image: "https://canifa.com/img/500/750/resize/5/t/5tw24w001-sk010-m-1-u.jpg",
		meta_title: "Áo nỉ có mũ unisex người lớn 5TW24W001-SK010",
		meta_description: "Áo nỉ có mũ unisex người lớn. Áo hoodie. Áo hoodie nam. Áo hoodie nữ.",
		name: "Áo nỉ có mũ unisex người lớn",
		short_description: "Áo nỉ có mũ unisex người lớn",
		status: 1,
		sku: "5TW24W001-SK010",
		slug: "ao-hoodie-unisex-nguoi-lon-5tw24w001-sk010",
		stock: 278894,
		materials: "60% cotton 40% polyester.",
		main_category: "Hàng mới",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy thùng, chế độ nhẹ nhàng.\nLà ở nhiệt độ trung bình 150 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 519200,
		image: "https://canifa.com/img/500/750/resize/5/t/5tw24w001-sb335-m-1-u.jpg",
		meta_title: "Áo hoodie unisex người lớn 5TW24W001-SB335",
		meta_description: "Áo nỉ có mũ unisex người lớn. Áo hoodie. Áo hoodie nam. Áo hoodie nữ.",
		name: "Áo nỉ có mũ unisex người lớn",
		short_description: "Áo nỉ có mũ unisex người lớn",
		status: 1,
		sku: "5TW24W001-SB335",
		slug: "ao-hoodie-unisex-nguoi-lon-5tw24w001-sb335",
		stock: 278892,
		materials: "60% cotton 40% polyester.",
		main_category: "Hàng mới",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy thùng, chế độ nhẹ nhàng.\nLà ở nhiệt độ trung bình 150 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 319200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tw24w006-sb358-thumb.jpg",
		meta_title: "Áo nỉ bé trai 2TW24W006-SB358",
		meta_description: "Áo nỉ bé trai",
		name: "Áo nỉ bé trai in hình Mickey",
		short_description: "Áo nỉ bé trai in hình Mickey",
		status: 1,
		sku: "2TW24W006-SB358",
		slug: "ao-ni-be-trai-2tw24w006-sb358",
		stock: 276983,
		materials: "70% cotton 30% polyester.",
		main_category: "Áo nỉ",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi ngay khi giặt xong.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 439200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tw24c005-sg305-thumb.jpg",
		meta_title: "Áo nỉ có mũ bé trai 2TW24C005",
		meta_description: "Áo nỉ có mũ bé trai. Áo hoodie bé trai. Áo hoodie.",
		name: "Áo nỉ bé trai phối mũ",
		short_description: "Áo nỉ bé trai phối mũ",
		status: 1,
		sku: "2TW24C005",
		slug: "ao-hoodie-be-trai-2tw24c005",
		stock: 277403,
		materials: "93% cotton 7% spandex.",
		main_category: "Áo",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi ngay khi giặt xong.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 239200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tl24w013-se477-thumb.jpg",
		meta_title: "Áo phông bé trai 2TL24W013-SE477",
		meta_description:
			"Áo phông bé trai. Áo phông bé trai dài tay. Áo phông dài tay bé trai. Áo thun dài tay bé trai. Áo thun bé trai dài tay. Áo thun dài tay. Áo phông dài tay.",
		name: "Áo phông dài tay bé trai có hình in",
		short_description: "Áo phông dài tay bé trai có hình in",
		status: 1,
		sku: "2TL24W013-SE477",
		slug: "ao-phong-be-trai-dai-tay-2tl24w013-se477",
		stock: 277127,
		materials: "61% polyester 35% cotton 4% spandex.",
		main_category: "Áo phông",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi ngay khi giặt xong.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 439200,
		image: "https://canifa.com/img/500/750/resize/2/o/2ot24w004-se014-thumb.jpg",
		meta_title: "Áo khoác chần bông bé trai 2OT24W004-SE014",
		meta_description:
			"Áo khoác chần bông bé trai. Áo phao bé trai. Áo chần bông bé trai. Áo khoác chần bông. Áo chần bông.",
		name: "Áo khoác chần bông bé trai",
		short_description: "Áo khoác chần bông bé trai",
		status: 1,
		sku: "2OT24W004-SE014",
		slug: "ao-khoac-chan-bong-be-trai-2ot24w004-se014",
		stock: 276931,
		materials: "Lớp ngoài: 100% polyester.\r\nLớp giữa:100% polyester.\r\nLớp lót: 100% polyester.",
		main_category: "Áo khoác chần bông",
		instruction:
			"Giặt tay ở nhiệt độ thường, không được ngâm.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nKhông được là.\r\nGiặt với sản phẩm cùng màu.",
		is_pre_order: false,
	},
	{
		final_price: 399200,
		image: "https://canifa.com/img/500/750/resize/2/b/2bp24w014-sg305-thumb.jpg",
		meta_title: "Quần nỉ bé trai 2BP24W014",
		meta_description: "Quần nỉ bé trai",
		name: "Quần nỉ bé trai",
		short_description: "Quần nỉ bé trai",
		status: 1,
		url_path: "quan-ni-be-trai-2bp24w014",
		sku: "2BP24W014",
		slug: "quan-ni-be-trai-2bp24w014",
		stock: 276821,
		materials: "93% cotton 7% spandex.",
		main_category: "Quần nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy khô ở nhiệt độ thấp.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 439200,
		image: "https://canifa.com/img/500/750/resize/1/t/1tw24c006-sk010-134-1-u.jpg",
		meta_title: "Áo nỉ có mũ bé gái 1TW24C006-SK010",
		meta_description: "Áo nỉ có mũ bé gái. Áo hoodie bé gái. Áo hoodie. Áo nỉ có mũ.",
		name: "Áo nỉ bé gái có hình in",
		short_description: "Áo nỉ bé gái có hình in",
		status: 1,
		sku: "1TW24C006-SK010",
		slug: "ao-hoodie-be-gai-1tw24c006-sk010",
		stock: 275683,
		materials: "60% cotton 40% polyester.\r\n",
		main_category: "Áo",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy thùng, chế độ nhẹ nhàng.\r\nLà ở nhiệt độ trung bình 150 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 279200,
		image: "https://canifa.com/img/500/750/resize/1/t/1te24w007-fm310-130-1-u.jpg",
		meta_title: "Áo len gilet bé gái 1TE24W007-FM310",
		meta_description: "Áo len gilet bé gái",
		name: "Áo len gilet bé gái hoạ tiết",
		short_description: "Áo len gilet bé gái hoạ tiết",
		status: 1,
		sku: "1TE24W007-FM310",
		slug: "ao-len-gilet-be-gai-1te24w007-fm310",
		stock: 277356,
		materials: "50% viscose 28% polyester.",
		main_category: "Áo len",
		instruction:
			"Giặt máy ở chế độ nhẹ,không ngâm.\nKhông sử dụng hóa chất tẩy có chứa clo.\nPhơi vắt ngang, trong bóng mát.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ trung bình 130 độ C.\nGiặt mặt trái sản phẩm.\nSản phẩm có nguy cơ xù lông, rụng lông và phai ra màu nhạt hơn.",
		is_pre_order: false,
	},
	{
		final_price: 199000,
		image: "https://canifa.com/img/500/750/resize/2/u/2us24a001-sk368-150-1-u.jpg",
		meta_title: "Combo 3 quần sịp đùi bé trai 2US24A001",
		meta_description: "Đồ lót. quần sịp bé trai. Quần lót bé trai. Quần sịp. Quần lót.",
		name: "Combo 3 quần sịp đùi bé trai",
		short_description: "Quần sịp đùi bé trai, chất liệu cotton pha mềm mại co dãn tốt, hình in sport khỏe khoắn.",
		status: 1,
		url_path: "quan-sip-be-trai-2us24a001",
		sku: "2US24A001",
		slug: "quan-sip-be-trai-2us24a001",
		stock: 270585,
		materials: "95% cotton 5% spandex.",
		main_category: "Đồ lót",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy khô ở nhiệt độ thấp.\r\nKhông là.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 104300,
		image: "https://canifa.com/img/500/750/resize/8/t/8ts24a005-sl178-thumb.jpg",
		meta_title: "Áo phông nam cotton cổ tròn dáng suông 8TS24A005",
		meta_description:
			"Áo phông cotton . áo thun cotton . Áo phông basic. Áo phông nam. Áo thun nam. Áo phông. Áo thun.",
		name: "Áo phông nam basic cổ tròn dáng suông",
		short_description: "Áo T-shirt nam cổ tròn phom regular",
		status: 1,
		url_path: "ao-phong-nam-8ts24a005",
		sku: "8TS24A005",
		slug: "ao-phong-nam-8ts24a005",
		stock: 266853,
		materials: "100% cotton",
		main_category: "Giá tốt",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy thùng, chế độ nhẹ nhàng.\r\nLà ở nhiệt độ trung bình 150 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 239200,
		image: "https://canifa.com/img/500/750/resize/6/b/6bp24w006-sk010-thumb.jpg",
		meta_title: "Quần nỉ nữ 6BP24W006",
		meta_description: "Quần nỉ nữ",
		name: "Quần nỉ nữ cotton USA",
		short_description: "Quần nỉ nữ giá tốt dáng basic. Chất liệu cotton USA mềm mịn, tạo cảm giác thoải mái khi mặc.",
		status: 1,
		sku: "6BP24W006",
		slug: "quan-ni-nu-6bp24w006",
		stock: 273747,
		materials: "60% cotton 40% polyester.",
		main_category: "Quần nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa clo.\r\nPhơi trong bóng mát.\r\nSấy thùng, chế độ nhẹ nhàng.\r\nLà ở nhiệt độ trung bình 150 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 319200,
		image: "https://canifa.com/img/500/750/resize/1/b/1bp24w002-sw011-thumb.jpg",
		meta_title: "Quần nỉ bé gái 1BP24W002",
		meta_description: "Quần nỉ bé gái",
		name: "Quần nỉ bé gái",
		short_description:
			"Quần dài jogger bé gái. Phom dáng cơ bản dễ kết hợp, màu sắc tươi sáng, bảng màu phong phú. Dây dệt cạp quần in chữ mới lạ, thời trang.\nNguyên liệu cào lông poly pha cotton ấm áp, mềm mại, dễ chịu khi sử dụng.",
		status: 1,
		sku: "1BP24W002",
		slug: "quan-ni-be-gai-1bp24w002",
		stock: 273845,
		materials: "65% polyester 35% cotton.",
		main_category: "Quần nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy khô ở nhiệt độ thấp.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 599200,
		image: "https://canifa.com/img/500/750/resize/1/s/1st24c002-sw015-thumb.jpg",
		meta_title: "Bộ quần áo bé gái 1ST24C002",
		meta_description: "Bộ quần áo bé gái",
		name: "Bộ quần áo bé gái cotton USA dài tay quần dài thêu hình",
		short_description:
			"Bộ quần áo dài tay quần dài bé gái. Áo kiểu ngắn, gấu bản to kết hợp quần ống suông hiện đại, năng động. Màu sắc tươi sáng, hình thêu dễ thương, phù hợp nhiều hoàn cảnh sử dụng.\nChất liệu cotton USA kết hợp hiệu ứng bề mặt Waffle hiện đại, mềm mại, ấm áp, tạo cảm giác dễ chịu khi sử dụng.",
		status: 1,
		sku: "1ST24C002",
		slug: "bo-quan-ao-be-gai-1st24c002",
		stock: 273858,
		materials: "72% cotton 24% polyester 4% spandex.",
		main_category: "Bộ nỉ/ Bộ quần áo",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy khô ở nhiệt độ thấp.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 209300,
		image: "https://canifa.com/img/500/750/resize/1/t/1to24w002-fp054-thumb.jpg",
		meta_title: "Áo kiểu bé gái 1TO24W002",
		meta_description: "Áo kiểu bé gái",
		name: "Áo kiểu bé gái phối bèo in hoạ tiết",
		short_description:
			"Áo kiểu bé gái với bèo trước ngực tạo sự nữ tính, phù hợp phối với nhiều loại trang phục cho bé gái.",
		status: 1,
		sku: "1TO24W002",
		slug: "ao-kieu-be-gai-1to24w002",
		stock: 273877,
		materials: "100% cotton.",
		main_category: "Áo kiểu",
		instruction:
			"Giặt máy ở nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy khô ở nhiệt độ trung bình.\r\nLà ở nhiệt độ trung bình 150 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 175200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tl24w002-sy199-thumb.jpg",
		meta_title: "Áo phông dài tay bé trai 2TL24W002",
		meta_description:
			"Áo phông dài tay bé trai. Áo thun dài tay bé trai. Áo thun bé trai dài tay. Áo phông bé trai dài tay. Áo thun. Áo phông.",
		name: "Áo phông bé trai cotton USA dài tay in hình Wolfoo",
		short_description:
			"Áo phông bé trai in hình Wolfoo tay raglan, phom dáng basic dễ mặc, chất liệu cotton thoải mái cho trẻ em.",
		status: 1,
		sku: "2TL24W002-SY199",
		slug: "ao-phong-be-trai-dai-tay-2tl24w002",
		stock: 273937,
		materials: "100% cotton.",
		main_category: "BST Wolfoo in Canifa",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi ngay khi giặt xong.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 419300,
		image: "https://canifa.com/img/500/750/resize/6/l/6ls24w006-sp328-thumb.jpg",
		meta_title: "Bộ mặc nhà nữ 6LS24W006",
		meta_description: "Bộ mặc nhà nữ",
		name: "Bộ mặc nhà nữ",
		short_description:
			"Bộ mặc nhà nữ quần suông, áo cổ cách điệu với các điểm nhấn cuốn bèo gấu tạo sự mềm mại nữ tính. Bề mặt vải dệt mix các sợi màu tạo nên 1 bộ sản phẩm đẹp và mới lạ.",
		status: 1,
		sku: "6LS24W006-SP328",
		slug: "bo-mac-nha-be-gai-6ls24w006",
		stock: 274317,
		materials: "87% polyester 8% rayon 5% spandex.",
		main_category: "Bộ nỉ/ Bộ quần áo",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi ngay khi giặt xong.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 119200,
		image: "https://canifa.com/img/500/750/resize/1/t/1ts24w001-sw011-thumb.jpg",
		meta_title: "Áo phông bé gái 1TS24W001",
		meta_description: "Áo phông bé gái. Áo thun bé gái. Áo phông. Áo thun.",
		name: "Áo phông bé gái thêu nơ dáng ôm",
		short_description:
			"Áo phông bé gái ngắn tay, cổ tròn. Phom dáng ôm sát, chi tiết trang trí cuốn bèo gấu tay, thêu nơ đính hạt trên ngực xinh xắn, hiện đại, dễ kết hợp trang phục cho bé gái",
		status: 1,
		sku: "1TS24W001",
		slug: "ao-phong-be-gai-1ts24w001",
		stock: 274479,
		materials: "63% rayon 34% polyester 3% spandex.",
		main_category: "Áo phông",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy khô ở nhiệt độ thấp.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 239200,
		image: "https://canifa.com/img/500/750/resize/1/t/1tw24w002-sp091-thumb.jpg",
		meta_title: "Áo nỉ bé gái 1TW24W002-SP091",
		meta_description: "Áo nỉ bé gái",
		name: "Áo nỉ bé gái có hình in",
		short_description:
			"Áo nỉ bé gái phom dáng cơ bản, màu sắc, hình in tươi sáng dễ thương, đễ dàng kết hợp trang phục và phù hợp nhiều hoàn cảnh sử dụng.",
		status: 1,
		sku: "1TW24W002-SP091",
		slug: "ao-ni-be-gai-1tw24w002-sp091",
		stock: 274588,
		materials: "70% cotton, 30% polyester.",
		main_category: "Áo nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nSấy khô ở nhiệt độ thấp.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 143200,
		image: "https://canifa.com/img/500/750/resize/1/d/1ds24w001-fm303-128-1-u.jpg",
		meta_title: "Váy liền bé gái 1DS24W001",
		meta_description: "Váy liền bé gái. Đầm liền bé gái. Váy bé gái. Đầm bé gái. Váy trẻ em. Đầm trẻ em.",
		name: "Váy liền bé gái dài tay có hình in",
		short_description:
			"Váy liền bé gái có hình in. Chi tiết cắt eo nữ tính, phù hợp với nhiều hoàn cảnh sử dụng.\r\nPhom regular cùng chất liệu cotton mang lại cảm giác thoải mái và dễ chịu cả ngày.",
		status: 1,
		sku: "1DS24W001-FM303",
		slug: "vay-be-gai-1ds24w001-fm303",
		stock: 274829,
		materials: "60% cotton 40% polyester.",
		main_category: "Giá tốt",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt riêng quần áo tối màu. Không ngâm. Sản phẩm dễ tạo xơ vón, loại bỏ bằng kéo hoặc máy cạo xơ.",
		is_pre_order: false,
	},
	{
		final_price: 175200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tl24w002-sa026-thumb.jpg",
		meta_title: "Áo phông dài tay bé trai 2TL24W002",
		meta_description:
			"Áo phông dài tay bé trai. Áo thun dài tay bé trai. Áo thun bé trai dài tay. Áo phông bé trai dài tay. Áo thun. Áo phông.",
		name: "Áo phông bé trai cotton USA dài tay in hình Wolfoo",
		short_description:
			"Áo phông bé trai in hình Wolfoo tay raglan, phom dáng basic dễ mặc, chất liệu cotton thoải mái cho trẻ em.",
		status: 1,
		sku: "2TL24W002-SA026",
		slug: "ao-phong-be-trai-dai-tay-2tl24w002-sa026",
		stock: 274928,
		materials: "100% cotton.",
		main_category: "BST Wolfoo in Canifa",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi ngay khi giặt xong.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 175200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tl24w002-sw001-thumb.jpg",
		meta_title: "Áo phông dài tay bé trai 2TL24W002",
		meta_description:
			"Áo phông dài tay bé trai. Áo thun dài tay bé trai. Áo thun bé trai dài tay. Áo phông bé trai dài tay. Áo thun. Áo phông.",
		name: "Áo phông bé trai cotton USA dài tay in hình Wolfoo",
		short_description:
			"Áo phông bé trai in hình Wolfoo tay raglan, phom dáng basic dễ mặc, chất liệu cotton thoải mái cho trẻ em.",
		status: 1,
		sku: "2TL24W002-SW001",
		slug: "ao-phong-be-trai-dai-tay-2tl24w002-sa001",
		stock: 274929,
		materials: "100% cotton.",
		main_category: "BST Wolfoo in Canifa",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi ngay khi giặt xong.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 419300,
		image: "https://canifa.com/img/500/750/resize/6/l/6ls24w006-sb137-thumb.jpg",
		meta_title: "Bộ mặc nhà nữ 6LS24W006-SB137",
		meta_description: "Bộ mặc nhà nữ",
		name: "Bộ mặc nhà nữ",
		short_description:
			"Bộ mặc nhà nữ quần suông, áo cổ cách điệu với các điểm nhấn cuốn bèo gấu tạo sự mềm mại nữ tính. Bề mặt vải dệt mix các sợi màu tạo nên 1 bộ sản phẩm đẹp và mới lạ.",
		status: 1,
		sku: "6LS24W006-SB137",
		slug: "bo-mac-nha-be-gai-6ls24w006-sb137",
		stock: 275221,
		materials: "87% polyester 8% rayon 5% spandex.",
		main_category: "Bộ nỉ/ Bộ quần áo",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. \r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi ngay khi giặt xong.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 639200,
		image: "https://canifa.com/img/500/750/resize/6/s/6st24w002-sr031-l-1-ghep-u.jpg",
		meta_title: "Bộ quần áo nữ 6ST24W002",
		meta_description: "Bộ quần áo nữ",
		name: "Bộ quần áo nỉ nữ có hình in",
		short_description:
			"Bộ nỉ nữ quần suông kết hợp với áo bo gấu và chi tiết lé phối khớp màu với hình đồ họa, tạo nên một sự lựa chọn hoàn hảo cho khách hàng.",
		status: 1,
		sku: "6ST24W002-SR031",
		slug: "bo-quan-ao-ni-nu-6st24w002-sr031",
		stock: 276768,
		main_category: "Bộ nỉ/ Bộ quần áo",
		is_pre_order: false,
	},
	{
		final_price: 639200,
		image: "https://canifa.com/img/500/750/resize/6/s/6st24w002-sa871-thumb.jpg",
		meta_title: "Bộ quần áo nữ 6ST24W002-SA871",
		meta_description: "Bộ quần áo nữ",
		name: "Bộ quần áo nỉ nữ có hình in",
		short_description:
			"Bộ nỉ nữ quần suông kết hợp với áo bo gấu và chi tiết lé phối khớp màu với hình đồ họa, tạo nên một sự lựa chọn hoàn hảo cho khách hàng.",
		status: 1,
		sku: "6ST24W002-SA871",
		slug: "bo-quan-ao-ni-nu-6st24w002-sa871",
		stock: 276769,
		main_category: "Bộ nỉ/ Bộ quần áo",
		is_pre_order: false,
	},
	{
		final_price: 639200,
		image: "https://canifa.com/img/500/750/resize/6/s/6st24w002-sg114-l-5-ghep-u.jpg",
		meta_title: "Bộ quần áo nữ 6ST24W002-SG114",
		meta_description: "Bộ quần áo nữ",
		name: "Bộ quần áo nỉ nữ có hình in",
		short_description:
			"Bộ nỉ nữ quần suông kết hợp với áo bo gấu và chi tiết lé phối khớp màu với hình đồ họa, tạo nên một sự lựa chọn hoàn hảo cho khách hàng.",
		status: 1,
		sku: "6ST24W002-SG114",
		slug: "bo-quan-ao-ni-nu-6st24w002-sg114",
		stock: 276770,
		main_category: "Bộ nỉ/ Bộ quần áo",
		is_pre_order: false,
	},
	{
		final_price: 479200,
		image: "https://canifa.com/img/500/750/resize/6/t/6tw24w006-sa871-thumb.jpg",
		meta_title: "Áo nỉ nữ 6TW24W006",
		meta_description: "Áo nỉ nữ",
		name: "Áo nỉ nữ",
		short_description: "Áo nỉ nữ cổ tròn dáng rộng, chi tiết đồ họa khớp màu với kẻ nhấn ở bo cổ và tay.",
		status: 1,
		url_path: "ao-ni-nu-6tw24w006",
		sku: "6TW24W006",
		slug: "ao-ni-nu-6tw24w006",
		stock: 277033,
		materials: "60% cotton 40% polyester.",
		main_category: "Áo nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy thùng, chế độ nhẹ nhàng.\r\nLà ở nhiệt độ trung bình 150 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 399200,
		image: "https://canifa.com/img/500/750/resize/6/t/6to24s012-sj898-thumb.jpg",
		meta_title: "Áo kiểu denim nữ 6TO24S012",
		meta_description: "Áo kiểu denim nữ",
		name: "Áo kiểu nữ cotton denim tay ngắn buộc nơ",
		short_description:
			"Áo denim tay ngắn, cổ tròn, kiểu buộc nơ, chất liệu mềm mại, thoải mái.\nChất liệu 100% cotton thấm hút mồ hôi tốt, mềm mại thoáng mát, tạo cảm giác thoải mái cho người mặc trong mọi hoạt động.",
		status: 1,
		url_path: "ao-kieu-nu-6to24s012",
		sku: "6TO24S012",
		slug: "ao-kieu-nu-6to24s012",
		stock: 275431,
		materials: "100% cotton.",
		main_category: "Áo kiểu",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ.\nGiặt riêng.\nKhông là lên chi tiết trang trí.\nSản phẩm có thể dây màu ra màu sáng hơn.",
		is_pre_order: false,
	},
	{
		final_price: 199200,
		image: "https://canifa.com/img/500/750/resize/6/t/6tl24w007-sw033-thumb.jpg",
		meta_title: "Áo phông dài tay nữ 6TL24W007",
		meta_description:
			"Áo phông dài tay nữ. Áo thun nữ dài tay. Áo phông nữ. Áo thun nữ. Áo thun nữ dài tay. Áo phông nữ dài tay.",
		name: "Áo phông nữ cổ vuống dáng ôm",
		short_description: "Áo phông nữ cổ vuống dáng ôm",
		status: 1,
		sku: "6TL24W007",
		slug: "ao-phong-nu-dai-tay-6tl24w007",
		stock: 275611,
		materials: "98% cotton 2% spandex.",
		main_category: "Áo phông",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt mặt trái sản phẩm.\r\nGiặt với sản phẩm cùng màu.",
		is_pre_order: false,
	},
	{
		final_price: 719200,
		image: "https://canifa.com/img/500/750/resize/6/o/6ot24w005-sg154-thumb.jpg",
		meta_title: "Áo khoác gió nữ 6OT24W005",
		meta_description: "Áo khoác gió nữ",
		name: "Áo khoác gió nữ hai lớp, cổ bẻ, kéo khóa",
		short_description: "Áo khoác gió nữ",
		status: 1,
		url_path: "ao-khoac-gio-nu-6ot24w005",
		sku: "6OT24W005",
		slug: "ao-khoac-gio-nu-6ot24w005",
		stock: 276275,
		main_category: "Áo khoác gió",
		is_pre_order: false,
	},
	{
		final_price: 479200,
		image: "https://canifa.com/img/500/750/resize/6/k/6ks24w010-sg154-thumb.jpg",
		meta_title: "Chân váy nữ 6KS24W010",
		meta_description: "Chân váy nữ",
		name: "Chân váy nữ chất liệu gió",
		short_description:
			"Chân váy gió mỏng dáng dài, phong cách khỏe khoắn với chi tiết túi hộp một bên, tạo nên một sản phẩm năng động, thoải mái phù hợp với giới trẻ. Chất liệu gió nhũ nhẹ, tạo cảm giác mới mẻ, trẻ trung.",
		status: 1,
		sku: "6KS24W010",
		slug: "chan-vay-nu-6ks24w010",
		stock: 275962,
		materials: '"Vải chính: 100% nylon.\r\nLớp lót: 100% polyester."',
		main_category: "Chân váy",
		instruction:
			"Giặt tay ở nhiệt độ thường, không ngâm.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nKhông là.\r\nGiặt với sản phẩm cùng màu.",
		is_pre_order: false,
	},
	{
		final_price: 349300,
		image: "https://canifa.com/img/500/750/resize/6/l/6ls24w003-fb538-thumb.jpg",
		meta_title: "Bộ mặc nhà nữ 6LS24W003-FB538",
		meta_description: "Bộ mặc nhà nữ",
		name: "Bộ mặc nhà nữ hoạ tiết",
		short_description: "Bộ mặc nhà nữ basic với các họa tiết vải khác nhau tạo nhiều sự lựa chọn và dễ ứng dụng.",
		status: 1,
		url_path: "bo-mac-nha-nu-6ls24w003-fb538",
		sku: "6LS24W003-FB538",
		slug: "bo-mac-nha-nu-6ls24w003-fb538",
		stock: 276249,
		materials: "95% cotton 5% spandex.",
		main_category: "Bộ nỉ/ Bộ quần áo",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường. Không sử dụng hóa chất tẩy có chứa Clo. Phơi trong bóng mát. Sấy khô ở nhiệt độ thấp. Là ở nhiệt độ thấp 110 độ C. Giặt với sản phẩm cùng màu. Không là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 319200,
		image: "https://canifa.com/img/500/750/resize/6/b/6bp24w007-sa871-thumb.jpg",
		meta_title: "Quần nỉ nữ 6BP24W007",
		meta_description: "Quần nỉ nữ",
		name: "Quần nỉ nữ",
		short_description: "Quần nỉ nữ",
		status: 1,
		url_path: "quan-ni-nu-6bp24w007",
		sku: "6BP24W007",
		slug: "quan-ni-nu-6bp24w007",
		stock: 275946,
		materials: "70% cotton, 30% polyester.",
		main_category: "Quần nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy khô ở nhiệt độ thấp.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 319200,
		image: "https://canifa.com/img/500/750/resize/2/t/2tw24w004-sw378-thumb.jpg",
		meta_title: "Áo nỉ bé trai 2TW24W004",
		meta_description: "Áo nỉ bé trai",
		name: "Áo nỉ bé trai cổ polo",
		short_description:
			"Áo nỉ bé trai cổ polo, chất liệu cotton pha, bề mặt interlock kiểu tạo sự lạ mắt mới lạ. Phom dáng rộng rãi thoải mái cho trẻ vận động và vui chơi cũng như sử dụng trong nhiều hoàn cảnh.",
		status: 1,
		sku: "2TW24W004",
		slug: "ao-ni-be-trai-2tw24w004",
		stock: 275795,
		materials: "52% polyester 48% cotton.",
		main_category: "Áo nỉ",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nLà ở nhiệt độ thấp 110 độ C.\r\nGiặt riêng quần áo tối màu. Không ngâm. Sản phẩm dễ tạo xơ vón, loại bỏ bằng kéo hoặc máy cạo xơ.",
		is_pre_order: false,
	},
	{
		final_price: 118300,
		image: "https://canifa.com/img/500/750/resize/2/t/2tw24w001-sb398-thumb.jpg",
		meta_title: "Áo nỉ bé trai 2TW24W001",
		meta_description: "Áo nỉ bé trai",
		name: "Áo nỉ bé trai cotton USA có hình in",
		short_description:
			"Áo nỉ dài tay chất liệu vảy cá độ dày vừa phải, phom dáng basic, hình in khỏe khoắn năng động, phù hợp cho thời \r\ntiết giao mùa.",
		status: 1,
		sku: "2TW24W001-SB398",
		slug: "ao-ni-be-trai-2tw24w001",
		stock: 274297,
		materials: "60% cotton 40% polyester.",
		main_category: "Giá tốt",
		instruction:
			"Giặt máy ở chế độ nhẹ, nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nSấy thùng, chế độ nhẹ nhàng.\r\nLà ở nhiệt độ trung bình 150 độ C.\r\nGiặt với sản phẩm cùng màu.\r\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 519200,
		image: "https://canifa.com/img/500/750/resize/2/o/2ot24w003-sb227-thumb.jpg",
		meta_title: "Áo khoác bé trai 2OT24W003",
		meta_description: "Áo khoác bé trai. Áo khoác gió bé trai. Áo khoác gió.",
		name: "Áo khoác lót lông bé trai",
		short_description:
			"Áo khoác bé trai có mũ. Phom dáng cơ bản dễ mặc, bên trong có lót lông ấm áp, mềm mại. Màu sắc phù hợp bé trai.\r\nNguyên liệu vái gió Polyester mỏng nhẹ, cản gió, chống thấm nước tốt. Bên trong lót lông giữ ấm tốt.Nguyên liệu vái gió Polyester mỏng nhẹ, cản gió, chống thấm nước tốt. Bên trong lót lông giữ ấm tốt.",
		status: 1,
		sku: "2OT24W003",
		slug: "ao-khoac-gio-be-trai-2ot24w003a",
		stock: 277901,
		materials: "Vải chính: 100% polyester.\r\nLớp lót: 100% polyester.",
		main_category: "Áo khoác gió",
		instruction:
			"Giặt máy ở nhiệt độ thường.\r\nKhông sử dụng hóa chất tẩy có chứa Clo.\r\nPhơi trong bóng mát.\r\nKhông sử dụng máy sấy.\r\nKhông được là.\r\nGiặt với sản phẩm cùng màu.\r\nTránh xa nguồn lửa.",
		is_pre_order: false,
	},
	{
		final_price: 479200,
		image: "https://canifa.com/img/500/750/resize/8/t/8tp24w003-se331-l-1-u.jpg",
		meta_title: "Áo polo nam 8TP24W003",
		meta_description: "Áo polo nam",
		name: "Áo polo nam dài tay",
		short_description:
			"Áo được thiết kế vừa vặn, thoải mái trong mọi hoạt động.\r\nThiết kế cổ bẻ, nẹp V đa năng dễ kết hợp nhiều lớp.\r\nDáng cơ bản dễ phối đồ.\r\nÁo phù hợp để mặc thường ngày, dễ dàng phối layer tạo nhiếu set thời trang đa phong cách (lịch sự, ấn tượng, trẻ trung....)",
		status: 1,
		url_path: "ao-polo-nam-dai-tay-8tp24w003",
		sku: "8TP24W003",
		slug: "ao-polo-nam-dai-tay-8tp24w003",
		stock: 278116,
		materials: "60% polyester 40% cotton.",
		main_category: "Áo polo",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm. Không sử dụng hóa chất tẩy có chứa Clo. Phơi ngay khi giặt xong. Không sử dụng máy sấy. Là ở nhiệt độ thấp 110 độ C. Giặt với sản phẩm cùng màu. Không là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 799200,
		image: "https://canifa.com/img/500/750/resize/6/o/6ot24w017-sp332-m-1-u.jpg",
		meta_title: "Áo khoác dạ nữ 6OT24W017",
		meta_description: "Áo khoác dạ nữ",
		name: "Áo dạ nữ dài tay, cổ tròn dáng suông vừa",
		short_description:
			"Áo dạ hai lớp dài tay, cổ tròn, cài cúc, dáng suông. Chất liệu dạ mịn mang lại cảm giác mềm mại, ấm áp, đứng dáng. Phù hợp với môi trường công sở, dạo phố.",
		status: 1,
		sku: "6OT24W017",
		slug: "ao-khoac-da-nu-6ot24w017",
		stock: 277492,
		materials:
			"Màu SP332, SE065: 90% polyester 10% rayon.\nMàu SK010: 80% polyester 20% rayon.\nLớp lót: 100% polyester.",
		main_category: "Đồ mặc ngoài",
		instruction:
			"Giặt máy ở nhiệt độ thường,không ngâm.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ.\nGiặt riêng.\nKhông là lên chi tiết trang trí.\nSản phẩm có thể dây màu ra màu sáng hơn.\n\nGiặt máy ở nhiệt độ thường.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ C.\nCó thể giặt khô.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
	{
		final_price: 279200,
		image: "https://canifa.com/img/500/750/resize/1/k/1ks24c008-fr061-128-1-u.jpg",
		meta_title: "Chân váy bé gái 1KS24C008",
		meta_description: "Chân váy bé gái",
		name: "Chân váy bé gái",
		short_description: "Chân váy bé gái",
		status: 1,
		sku: "1KS24C008",
		slug: "chan-vay-be-gai-1ks24c008",
		stock: 277690,
		materials: "Vải chính: 100% polyester.\nLớp lót: 100% polyester.",
		main_category: "Chân váy",
		instruction:
			"Giặt tay ở nhiệt độ thường, không được ngâm.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nKhông được là.\nGiặt với sản phẩm cùng màu.",
		is_pre_order: false,
	},
	{
		final_price: 479200,
		image: "https://canifa.com/img/500/750/resize/6/b/6bp24w004-sk010-l-1-u.jpg",
		meta_title: "Quần dài nữ 6BP24W004",
		meta_description: "Quần dài nữ",
		name: "Quần dài nữ ống vẩy",
		short_description:
			"Quần dài ống vẩy, chất liệu polyester dầy dặn, co dãn nhẹ, phù hợp môi trường công sở.\nChất liệu polyester tạo cảm giác lịch sự phù hợp văn phòng công sở, mà vẫn thoải mái cho người mặc.",
		status: 1,
		sku: "6BP24W004",
		slug: "quan-dai-nu-6bp24w004",
		stock: 277430,
		materials: "100% polyester.",
		main_category: "Quần vải",
		instruction:
			"Giặt tay ở nhiệt độ thường,không ngâm.\nKhông sử dụng hóa chất tẩy có chứa Clo.\nPhơi trong bóng mát.\nKhông sử dụng máy sấy.\nLà ở nhiệt độ thấp 110 độ C.\nGiặt với sản phẩm cùng màu.\nKhông là lên chi tiết trang trí.",
		is_pre_order: false,
	},
];